after_script: greenkeeper-lockfile-upload

before_install: npm i -g greenkeeper-lockfile npm@latest

before_script: greenkeeper-lockfile-update

install: npm i && npm i general-language-syntax ts-gls typescript 

language: node_js

node_js:
  - "node"

script:
  npm run verify
